# Generated by Django 5.2 on 2025-04-12 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(choices=[('bait', 'Наживка'), ('feed', 'Прикормка'), ('lure', 'Искусственная приманка')], max_length=10, verbose_name='Тип приманки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='baits/', verbose_name='Изображение')),
                ('target_fish', models.CharField(choices=[('universal', 'Универсальная'), ('predator', 'Для хищников'), ('peaceful', 'Для мирных рыб')], default='universal', max_length=10, verbose_name='Целевая рыба')),
                ('price_category', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10, verbose_name='Категория цены')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг (1-5)')),
            ],
            options={
                'verbose_name': 'Приманка',
                'verbose_name_plural': 'Приманки',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название рыбы')),
                ('scientific_name', models.CharField(blank=True, max_length=100, verbose_name='Научное название')),
                ('type', models.CharField(choices=[('predator', 'Хищник'), ('peaceful', 'Мирная'), ('omnivore', 'Всеядная')], max_length=10, verbose_name='Тип питания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish/', verbose_name='Изображение')),
                ('habitat', models.CharField(choices=[('fresh', 'Пресная'), ('salt', 'Солёная'), ('brackish', 'Солоноватая')], default='fresh', max_length=20, verbose_name='Тип воды')),
                ('area', models.CharField(max_length=100, verbose_name='Ареал обитания')),
                ('season_activity', models.CharField(choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('all_season', 'Круглый год')], max_length=10, verbose_name='Сезон активности')),
                ('best_catch_time', models.CharField(blank=True, choices=[('morning', 'Утро'), ('afternoon', 'День'), ('evening', 'Вечер'), ('night', 'Ночь'), ('all_day', 'Круглые сутки')], help_text='Например: утро, день, вечер, ночь', max_length=100, verbose_name='Лучшее время для ловли')),
                ('optimal_temperature', models.IntegerField(blank=True, null=True, verbose_name='Оптимальная температура воды (°C)')),
                ('temperature_range', models.CharField(blank=True, help_text='Например: 15-22', max_length=50, verbose_name='Диапазон температур активности (°C)')),
                ('is_red_book', models.BooleanField(default=False, verbose_name='В Красной книге')),
                ('avg_weight', models.FloatField(blank=True, null=True, verbose_name='Средний вес (кг)')),
                ('max_weight', models.FloatField(blank=True, null=True, verbose_name='Максимальный вес (кг)')),
                ('avg_length', models.FloatField(blank=True, null=True, verbose_name='Средняя длина (см)')),
            ],
            options={
                'verbose_name': 'Рыба',
                'verbose_name_plural': 'Рыбы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FishBaitRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency', models.PositiveSmallIntegerField(help_text='Оценка от 1 (минимальная) до 5 (максимальная)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Эффективность (1-5)')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные советы', verbose_name='Заметки')),
                ('bait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.bait', verbose_name='Приманка')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_app.fish', verbose_name='Рыба')),
            ],
            options={
                'verbose_name': 'Связь рыба-приманка',
                'verbose_name_plural': 'Связи рыба-приманка',
                'ordering': ['-efficiency'],
                'unique_together': {('fish', 'bait')},
            },
        ),
    ]
